DBSQLONE/Models/Tables/CleanLocation.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DBSQLONE.Models.Tables
{
    public class CleanLocation
    {
        public int Id { get; set; }
        public int IdPlayer { get; set; }
        public int IdLocation { get; set; }
        public DateTime Passed { get; set; }
    }
}

DBSQLONE/Models/Tables/GetItem.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DBSQLONE.Models.Tables
{
    public class GetItem
    {
        public int Id { get; set; }
        public int IdItem { get; set; }
        public int IdPlayer { get; set; }
        public DateTime Received { get; set; }
    }
}

DBSQLONE/Models/Tables/GetItems.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DBSQLONE.Models.Tables
{
    public class GetItemsGetItems
    {
        public int Id { get; set; }
        public int IdItem { get; set; }
        public int IdPlayer { get; set; }
        public DateTime Received { get; set; }
    }
}

DBSQLONE/Models/Tables/Guild.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DBSQLONE.Models.Tables
{
    public class Guild
    {
        public int Id { get; set; }
        public string NameGuild { get; set; }
        public string DescriptionGuild { get; set; }
        public int CreatorIdPlayer { get; set; }
        public DateTime Created { get; set; }

    }
}

DBSQLONE/Models/Tables/GuildMember.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DBSQLONE.Models.Tables
{
    public class GuildMember
    {
        public int Id { get; set; }
        public int IdPlayer { get; set; }
        public int IdGuild { get; set; }
    }
}

DBSQLONE/Models/Tables/Item.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DBSQLONE.Models.Tables
{
    public class Item
    {
        public int Id { get; set; }
        public int IdType { get; set; }
        public string NameItem { get; set; }
        public string DescriptionItem { get; set; }
    }
}

DBSQLONE/Models/Tables/Location.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DBSQLONE.Models.Tables
{
    public class Location
    {
        public int Id { get; set; }
        public string NameLocation { get; set; }
        public string DescriptionLocations { get; set; }
    }
}

DBSQLONE/Models/Tables/Player.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DBSQLONE.Models
{
    public class Player
    {
        public int Id { get; set; }
        public string Nickname { get; set; }
        public string Pass { get; set; }
        public string Email { get; set; }
        public DateTime Registered { get; set; }
    }
}

DBSQLONE/Pages/Tables/CleanLocations.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DBSQLONE.Models.Tables;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Data.Common;
using MySql.Data.MySqlClient;
using DBSQLONE.Models;

namespace DBSQLONE.Pages.Tables
{
    public class CleanLocationsModel : PageModel
    {
        public List<CleanLocation> Table = new List<CleanLocation>();
        public string ErrorMessage { get; set; }

        public void OnGet()
        {
            ErrorMessage = Request.Cookies["ErrorMessage"];
            Response.Cookies.Append("ErrorMessage", "");
            MySqlConnection conn = DatabaseConnection.GetMyDB();
            try
            {
                conn.Open();
                string sql = "SELECT * FROM CleanLocations";
                MySqlCommand cmd = new MySqlCommand
                {
                    Connection = conn,
                    CommandText = sql
                };
                using (DbDataReader reader = cmd.ExecuteReader())
                {
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            Table.Add(new CleanLocation
                            {
                                Id = Convert.ToInt32(reader.GetValue(reader.GetOrdinal("Id"))),
                                IdPlayer = Convert.ToInt32(reader.GetValue(reader.GetOrdinal("IdPlayer"))),
                                IdLocation = Convert.ToInt32(reader.GetValue(reader.GetOrdinal("IdLocation"))),
                                Passed = Convert.ToDateTime(reader.GetValue(reader.GetOrdinal("Passed")))
                            });
                        }
                    }
                }
            }
            catch (Exception e)
            {
                ErrorMessage = e.Message;
            }
            finally
            {
                conn.Close();
                conn.Dispose();
            }
        }

        public IActionResult OnPostUpdate(CleanLocation cleanLocation)
        {
            MySqlConnection conn = DatabaseConnection.GetMyDB();
            try
            {
                conn.Open();
                string sql = "UPDATE CleanLocations SET IdPlayer = @IdPlayer, IdLocation = @IdLocation, Passed = @Passed WHERE Id = @Id";
                MySqlCommand cmd = conn.CreateCommand();
                cmd.CommandText = sql;
                cmd.Parameters.Add("@Id", MySqlDbType.Int32).Value = cleanLocation.Id;
                cmd.Parameters.Add("@IdPlayer", MySqlDbType.Int32).Value = cleanLocation.IdPlayer;
                cmd.Parameters.Add("@IdLocation", MySqlDbType.Int32).Value = cleanLocation.IdLocation;
                cmd.Parameters.Add("@Passed", MySqlDbType.Date).Value = cleanLocation.Passed;
                cmd.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                Response.Cookies.Append("ErrorMessage", e.Message);
            }
            finally
            {
                conn.Close();
                conn.Dispose();
            }
            return RedirectToPage();
        }

        public IActionResult OnPostDelete(CleanLocation cleanLocation)
        {
            MySqlConnection conn = DatabaseConnection.GetMyDB();
            try
            {
                conn.Open();
                string sql = "DELETE FROM CleanLocations WHERE Id = @Id";
                MySqlCommand cmd = conn.CreateCommand();
                cmd.CommandText = sql;
                cmd.Parameters.Add("@Id", MySqlDbType.Int32).Value = cleanLocation.Id;
                cmd.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                Response.Cookies.Append("ErrorMessage", e.Message);
            }
            finally
            {
                conn.Close();
                conn.Dispose();
            }
            return RedirectToPage();
        }

        public IActionResult OnPostInsert(CleanLocation cleanLocation)
        {
            MySqlConnection conn = DatabaseConnection.GetMyDB();
            try
            {
                conn.Open();
                string sql = "INSERT CleanLocations(IdPlayer, IdLocation, Passed) VALUES(@IdPlayer, @IdLocation, @Passed)";
                MySqlCommand cmd = conn.CreateCommand();
                cmd.CommandText = sql;
                cmd.Parameters.Add("@IdPlayer", MySqlDbType.Int32).Value = cleanLocation.IdPlayer;
                cmd.Parameters.Add("@IdLocation", MySqlDbType.Int32).Value = cleanLocation.IdLocation;
                cmd.Parameters.Add("@Passed", MySqlDbType.Date).Value = cleanLocation.Passed;

                cmd.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                Response.Cookies.Append("ErrorMessage", e.Message);
            }
            finally
            {
                conn.Close();
                conn.Dispose();
            }
            return RedirectToPage();
        }
    }
}

DBSQLONE/Pages/Tables/GetItems.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DBSQLONE.Models.Tables;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Data.Common;
using MySql.Data.MySqlClient;
using DBSQLONE.Models;

namespace DBSQLONE.Pages.Tables
{
    public class GetItemsModel : PageModel
    {
        public List<GetItem> Table = new List<GetItem>();
        public string ErrorMessage { get; set; }

        public void OnGet()
        {
            ErrorMessage = Request.Cookies["ErrorMessage"];
            Response.Cookies.Append("ErrorMessage", "");
            MySqlConnection conn = DatabaseConnection.GetMyDB();
            try
            {
                conn.Open();
                string sql = "SELECT * FROM GetItems";
                MySqlCommand cmd = new MySqlCommand
                {
                    Connection = conn,
                    CommandText = sql
                };
                using (DbDataReader reader = cmd.ExecuteReader())
                {
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            Table.Add(new GetItem
                            {
                                Id = Convert.ToInt32(reader.GetValue(reader.GetOrdinal("Id"))),
                                IdItem = Convert.ToInt32(reader.GetValue(reader.GetOrdinal("IdItem"))),
                                IdPlayer = Convert.ToInt32(reader.GetValue(reader.GetOrdinal("IdPlayer"))),
                                Received = Convert.ToDateTime(reader.GetValue(reader.GetOrdinal("Received")))

                            });
                        }
                    }
                }
            }
            catch (Exception e)
            {
                ErrorMessage = e.Message;
            }
            finally
            {
                conn.Close();
                conn.Dispose();
            }
        }

        public IActionResult OnPostUpdate(GetItem getItem)
        {
            MySqlConnection conn = DatabaseConnection.GetMyDB();
            try
            {
                conn.Open();
                string sql = "UPDATE GetItems SET IdItem = @IdItem, IdPlayer = @IdPlayer, Received = @Received WHERE Id = @Id";
                MySqlCommand cmd = conn.CreateCommand();
                cmd.CommandText = sql;
                cmd.Parameters.Add("@Id", MySqlDbType.Int32).Value = getItem.Id;
                cmd.Parameters.Add("@IdItem", MySqlDbType.Int32).Value = getItem.IdItem;
                cmd.Parameters.Add("@IdPlayer", MySqlDbType.Int32).Value = getItem.IdPlayer;
                cmd.Parameters.Add("@Received", MySqlDbType.Date).Value = getItem.Received;
                cmd.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                Response.Cookies.Append("ErrorMessage", e.Message);
            }
            finally
            {
                conn.Close();
                conn.Dispose();
            }
            return RedirectToPage();
        }

        public IActionResult OnPostDelete(GetItem getItem)
        {
            MySqlConnection conn = DatabaseConnection.GetMyDB();
            try
            {
                conn.Open();
                string sql = "DELETE FROM GetItems WHERE Id = @Id";
                MySqlCommand cmd = conn.CreateCommand();
                cmd.CommandText = sql;
                cmd.Parameters.Add("@Id", MySqlDbType.Int32).Value = getItem.Id;
                cmd.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                Response.Cookies.Append("ErrorMessage", e.Message);
            }
            finally
            {
                conn.Close();
                conn.Dispose();
            }
            return RedirectToPage();
        }

        public IActionResult OnPostInsert(GetItem getItem)
        {
            MySqlConnection conn = DatabaseConnection.GetMyDB();
            try
            {
                conn.Open();
                string sql = "INSERT GetItems(IdItem, IdPlayer, Received) VALUES(@IdItem, @IdPlayer, @Received)";
                MySqlCommand cmd = conn.CreateCommand();
                cmd.CommandText = sql;
                cmd.Parameters.Add("@IdItem", MySqlDbType.Int32).Value = getItem.IdItem;
                cmd.Parameters.Add("@IdPlayer", MySqlDbType.Int32).Value = getItem.IdPlayer;
                cmd.Parameters.Add("@Received", MySqlDbType.Date).Value = getItem.Received;
                cmd.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                Response.Cookies.Append("ErrorMessage", e.Message);
            }
            finally
            {
                conn.Close();
                conn.Dispose();
            }
            return RedirectToPage();
        }
    }
}

DBSQLONE/Pages/Tables/GuildMembers.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using DBSQLONE.Models.Tables;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Data;
using System.Data.Common;
using MySql.Data.MySqlClient;
using DBSQLONE.Models;

namespace DBSQLONE.Pages.Tables
{
    public class GuildMembersModel : PageModel
    {
        public List<GuildMember> Table = new List<GuildMember>();
        public string ErrorMessage { get; set; }

        public void OnGet()
        {
            ErrorMessage = Request.Cookies["ErrorMessage"];
            Response.Cookies.Append("ErrorMessage", "");
            MySqlConnection conn = DatabaseConnection.GetMyDB();
            try
            {
                conn.Open();
                string sql = "SELECT * FROM GuildMembers";
                MySqlCommand cmd = new MySqlCommand
                {
                    Connection = conn,
                    CommandText = sql
                };
                using (DbDataReader reader = cmd.ExecuteReader())
                {
                    if (reader.HasRows)
                    {
                        while (reader.Read())
                        {
                            Table.Add(new GuildMember
                            {
                                Id = Convert.ToInt32(reader.GetValue(reader.GetOrdinal("Id"))),
                                IdPlayer = Convert.ToInt32(reader.GetValue(reader.GetOrdinal("IdPlayer"))),
                                IdGuild = Convert.ToInt32(reader.GetValue(reader.GetOrdinal("IdGuild")))
                            });
                        }
                    }
                }
            }
            catch (Exception e)
            {
                ErrorMessage = e.Message;
            }
            finally
            {
                conn.Close();
                conn.Dispose();
            }
        }

        public IActionResult OnPostUpdate(GuildMember guildMember)
        {
            MySqlConnection conn = DatabaseConnection.GetMyDB();
            try
            {
                conn.Open();
                string sql = "UPDATE GuildMembers SET IdPlayer = @IdPlayer, IdGuild = @IdGuild WHERE Id = @Id";
                MySqlCommand cmd = conn.CreateCommand();
                cmd.CommandText = sql;
                cmd.Parameters.Add("@Id", MySqlDbType.Int32).Value = guildMember.Id;
                cmd.Parameters.Add("@IdPlayer", MySqlDbType.Int32).Value = guildMember.IdPlayer;
                cmd.Parameters.Add("@IdGuild", MySqlDbType.Int32).Value = guildMember.IdGuild;
                cmd.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                Response.Cookies.Append("ErrorMessage", e.Message);
            }
            finally
            {
                conn.Close();
                conn.Dispose();
            }
            return RedirectToPage();
        }

        public IActionResult OnPostDelete(GuildMember guildMember)
        {
            MySqlConnection conn = DatabaseConnection.GetMyDB();
            try
            {
                conn.Open();
                string sql = "DELETE FROM GuildMembers WHERE Id = @Id";
                MySqlCommand cmd = conn.CreateCommand();
                cmd.CommandText = sql;
                cmd.Parameters.Add("@Id", MySqlDbType.Int32).Value = guildMember.Id;
                cmd.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                Response.Cookies.Append("ErrorMessage", e.Message);
            }
            finally
            {
                conn.Close();
                conn.Dispose();
            }
            return RedirectToPage();
        }

        public IActionResult OnPostInsert(GuildMember guildMember)
        {
            MySqlConnection conn = DatabaseConnection.GetMyDB();
            try
            {
                conn.Open();
                string sql = "INSERT GuildMembers(IdPlayer, IdGuild) VALUES(@IdPlayer, @IdGuild)";
                MySqlCommand cmd = conn.CreateCommand();
                cmd.CommandText = sql;
                cmd.Parameters.Add("@IdPlayer", MySqlDbType.Int32).Value = guildMember.IdPlayer;
                cmd.Parameters.Add("@IdGuild", MySqlDbType.Int32).Value = guildMember.IdGuild;
                cmd.ExecuteNonQuery();
            }
            catch (Exception e)
            {
                Response.Cookies.Append("ErrorMessage", e.Message);
            }
            finally
            {
                conn.Close();
                conn.Dispose();
            }
            return RedirectToPage();
        }
    }
}

DBSQLONE/Pages/Tables/CleanLocations.cshtml
@page
@model DBSQLONE.Pages.Tables.CleanLocationsModel
@{
    ViewData["Title"] = "Пройденные локации";
}

<table class="table">
    <thead>
        <tr><th>Ид</th><th>Ид Игрока</th><th>Ид Локации</th><th>Дата прохождения</th></tr>
    </thead>
    <tbody>
        @foreach (var Row in Model.Table)
        {
            <tr>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="Id" value="@Row.Id" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="IdPlayer" value="@Row.IdPlayer" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="IdLocation" value="@Row.IdLocation" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="Passed" value="@Row.Passed.ToShortDateString()" /></td>
                <td><form method="post" id="@Row.Id"><input type="submit" asp-page-handler="Update" value="Изменить" /></form></td>
                <td><input form="@Row.Id" type="submit" asp-page-handler="Delete" value="Удалить" /></td>
            </tr>
        }
        <tr>
            <td>*</td>
            <td><input form="Insert" type="number" name="IdPlayer" /></td>
            <td><input form="Insert" type="number" name="IdLocation" /></td>
            <td><input form="Insert" type="date" name="Passed" /></td>
            <td><form method="post" id="Insert"><input type="submit" asp-page-handler="Insert" value="Добавить" /></form></td>
        </tr>
    </tbody>
</table>
<h3><font color="#FF0000">@Model.ErrorMessage</font></h3>

DBSQLONE/Pages/Tables/GetItems.cshtml
@page
@model DBSQLONE.Pages.Tables.GetItemsModel
@{
    ViewData["Title"] = "Полученные предметы";
}

<table class="table">
    <thead>
        <tr><th>Ид</th><th>Ид Предмета</th><th>Ид Игрока</th><th>Дата получения</th></tr>
    </thead>
    <tbody>
        @foreach (var Row in Model.Table)
        {
            <tr>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="Id" value="@Row.Id" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="IdItem" value="@Row.IdItem" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="IdPlayer" value="@Row.IdPlayer" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="Received" value="@Row.Received.ToShortDateString()" /></td>
                <td><form method="post" id="@Row.Id"><input type="submit" asp-page-handler="Update" value="Изменить" /></form></td>
                <td><input form="@Row.Id" type="submit" asp-page-handler="Delete" value="Удалить" /></td>
            </tr>
        }
        <tr>
            <td>*</td>
            <td><input form="Insert" type="number" name="IdItem" /></td>
            <td><input form="Insert" type="number" name="IdPlayer" /></td>
            <td><input form="Insert" type="date" name="Received" /></td>
            <td><form method="post" id="Insert"><input type="submit" asp-page-handler="Insert" value="Добавить" /></form></td>
        </tr>
    </tbody>
</table>
<h3><font color="#FF0000">@Model.ErrorMessage</font></h3>

DBSQLONE/Pages/Tables/GuildMembers.cshtml
@page
@model DBSQLONE.Pages.Tables.GuildMembersModel
@{
    ViewData["Title"] = "Состав Гильдий";
}

<table class="table">
    <thead>
        <tr><th>Ид</th><th>Ид Игрока</th><th>Ид Гильдии</th></tr>
    </thead>
    <tbody>
        @foreach (var Row in Model.Table)
        {
            <tr>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="Id" value="@Row.Id" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="IdPlayer" value="@Row.IdPlayer" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="IdGuild" value="@Row.IdGuild" /></td>
                <td><form method="post" id="@Row.Id"><input type="submit" asp-page-handler="Update" value="Изменить" /></form></td>
                <td><input form="@Row.Id" type="submit" asp-page-handler="Delete" value="Удалить" /></td>
            </tr>
        }
        <tr>
            <td>*</td>
            <td><input form="Insert" type="number" name="IdPlayer" /></td>
            <td><input form="Insert" type="number" name="IdGuild" /></td>
            <td><form method="post" id="Insert"><input type="submit" asp-page-handler="Insert" value="Добавить" /></form></td>
        </tr>
    </tbody>
</table>
<h3><font color="#FF0000">@Model.ErrorMessage</font></h3>

DBSQLONE/Pages/Tables/Guilds.cshtml
@page
@model DBSQLONE.Pages.Tables.GuildsModel
@{
    ViewData["Title"] = "Гильдии";
}

<table class="table">
    <thead>
        <tr><th>Ид</th><th>Название</th><th>Описание</th><th>Ид создателя</th><th>Дата создания</th></tr>
    </thead>
    <tbody>
        @foreach (var Row in Model.Table)
        {
            <tr>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="Id" value="@Row.Id" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="NameGuild" value="@Row.NameGuild" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="DescriptionGuild" value="@Row.DescriptionGuild" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="CreatorIdPlayer" value="@Row.CreatorIdPlayer" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="Created" value="@Row.Created.ToShortDateString()" /></td>
                <td><form method="post" id="@Row.Id"><input type="submit" asp-page-handler="Update" value="Изменить" /></form></td>
                <td><input form="@Row.Id" type="submit" asp-page-handler="Delete" value="Удалить" /></td>
            </tr>
        }
        <tr>
            <td>*</td>
            <td><input form="Insert" type="text" name="NameGuild" /></td>
            <td><input form="Insert" type="text" name="DescriptionGuild" /></td>
            <td><input form="Insert" type="number" name="CreatorIdPlayer" /></td>
            <td><input form="Insert" type="date" name="Created" /></td>
            <td><form method="post" id="Insert"><input type="submit" asp-page-handler="Insert" value="Добавить" /></form></td>
        </tr>
    </tbody>
</table>
<h3><font color="#FF0000">@Model.ErrorMessage</font></h3>

DBSQLONE/Pages/Tables/Items.cshtml
@page
@model DBSQLONE.Pages.Tables.ItemsModel
@{
    ViewData["Title"] = "Предметы";
}

<table class="table">
    <thead>
        <tr><th>Ид</th><th>Тип</th><th>Название</th><th>Описание</th></tr>
    </thead>
    <tbody>
        @foreach (var Row in Model.Table)
        {
            <tr>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="Id" value="@Row.Id" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="IdType" value="@Row.IdType" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="NameItem" value="@Row.NameItem" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="DescriptionItem" value="@Row.DescriptionItem" /></td>
                <td><form method="post" id="@Row.Id"><input type="submit" asp-page-handler="Update" value="Изменить" /></form></td>
                <td><input form="@Row.Id" type="submit" asp-page-handler="Delete" value="Удалить" /></td>
            </tr>
        }
        <tr>
            <td>*</td>
            <td><input form="Insert" type="text" name="IdType" /></td>
            <td><input form="Insert" type="text" name="NameItem" /></td>
            <td><input form="Insert" type="text" name="DescriptionItem" /></td>
            <td><form method="post" id="Insert"><input type="submit" asp-page-handler="Insert" value="Добавить" /></form></td>
        </tr>
    </tbody>
</table>
<h3><font color="#FF0000">@Model.ErrorMessage</font></h3>

DBSQLONE/Pages/Tables/Locations.cshtml
@page
@model DBSQLONE.Pages.Tables.LocationsModel
@{
    ViewData["Title"] = "Локации";
}

<table class="table">
    <thead>
        <tr><th>Ид</th><th>Название</th><th>Описание</th></tr>
    </thead>
    <tbody>
        @foreach (var Row in Model.Table)
        {
            <tr>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="Id" value="@Row.Id" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="NameLocation" value="@Row.NameLocation" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="DescriptionLocations" value="@Row.DescriptionLocations" /></td>
                <td><form method="post" id="@Row.Id"><input type="submit" asp-page-handler="Update" value="Изменить" /></form></td>
                <td><input form="@Row.Id" type="submit" asp-page-handler="Delete" value="Удалить" /></td>
            </tr>
        }
        <tr>
            <td>*</td>
            <td><input form="Insert" type="text" name="NameLocation" /></td>
            <td><input form="Insert" type="text" name="DescriptionLocations" /></td>
            <td><form method="post" id="Insert"><input type="submit" asp-page-handler="Insert" value="Добавить" /></form></td>
        </tr>
    </tbody>
</table>
<h3><font color="#FF0000">@Model.ErrorMessage</font></h3>

DBSQLONE/Pages/Tables/TypesItem.cshtml
@page
@model DBSQLONE.Pages.Tables.TypesItemModel
@{
    ViewData["Title"] = "Типы предметов";
}

<table class="table">
    <thead>
        <tr><th>Ид</th><th>Название</tr>
    </thead>
    <tbody>
        @foreach (var Row in Model.Table)
        {
            <tr>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="Id" value="@Row.Id" /></td>
                <td><input form="@Row.Id" style="border-width:0;" type="text" name="NameType" value="@Row.NameType" /></td>
                <td><form method="post" id="@Row.Id"><input type="submit" asp-page-handler="Update" value="Изменить" /></form></td>
                <td><input form="@Row.Id" type="submit" asp-page-handler="Delete" value="Удалить" /></td>
            </tr>
        }
        <tr>
            <td>*</td>
            <td><input form="Insert" type="text" name="NameType" /></td>
            <td><form method="post" id="Insert"><input type="submit" asp-page-handler="Insert" value="Добавить" /></form></td>
        </tr>
    </tbody>
</table>
<h3><font color="#FF0000">@Model.ErrorMessage</font></h3>